# -*- coding: utf-8 -*-
"""notebook57fc6f029f

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebook#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/thevishal435/notebook57fc6f029f.fa344f88-cdf3-4c5b-88c9-9138fa355d2f.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260908/auto/storage/goog4_request%26X-Goog-Date%3D20260908T062425Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D57f30f8e5192b06e7a5bbb7766f9bfd1e7e8bdbc9b93c4434e6ed90899b4beb0274d9b8faf89c1ee8bff36c69ca4745c68267a0e0257d969608a0630e2b0fc702e8e67b50121a40998ab916cd5b175c3b7ba246208e133cb56d4d38d51afdd0b78c440ac190f7be3fee592511519962cbefdede7c76ac8afb97a379092a08011ef66ef68023684b709161065e0a80f5a927f55b4c56f60e9c62e44cda462aad1ebb2bda98db4d8b69d47945aa6605163c6ee09d76986e04fb1f05c952ff529712cb2e1dc9fdd84d8268704695114b1b6d13ab31974da4110297e64b06c628173fa860ba3809c1ea943b13bc70233543492dbda7027697507d84abf49980975c5
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

(X_train,y_train),(X_test,y_test) = keras.datasets.mnist.load_data()

X_train.shape

y_train

import matplotlib.pyplot as plt
plt.imshow(X_train[59999])

X_train = X_train/255
X_test = X_test/255

model = Sequential()

model.add(Flatten(input_shape=(28,28)))
model.add(Dense(128,activation='relu'))
model.add(Dense(10,activation='softmax'))

model.summary()

model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam')

history = model.fit(X_train,y_train,epochs=10,validation_split=0.2)

y_prob = model.predict(X_test)

y_pred = y_prob.argmax(axis=1)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.imshow(X_test[0])

model.predict(X_test[0].reshape(1,28,28)).argmax(axis=1)

plt.imshow(X_test[56])

model.predict(X_test[56].reshape(1,28,28)).argmax(axis=1)

